### ISSUE TITLE
下载是否消耗下载额度？

### ISSUE THREAD

**Issue by Brave-peng** [Halyul/vol_moe-downloader#1]
您好，我对爬虫和js并不是非常了解，看代码的时候，大致感觉是利用账号信息登录，然后顺序下载list当中的漫画。
因此，我想请问，该爬虫是突破了下载额度限制，真正找到了对应的漫画，还是利用下载按钮发起了请求？

**Comment by Halyul** [comment]
这个工具仅仅是（我自己）用来挂机下载漫画 初衷只是想有一个小玩意帮我一直下载我没有的漫画
这个工具并不能突破下载速度限制/额度限制 仅仅是模拟用户操作去下载漫画（好像还有bug）

**Comment by Brave-peng** [comment]
感谢你的回答，你的代码我觉得很cool~
